In [ ]:
from ollama import chat

response = chat(
    model="qwen3.5:4b",
    messages=[
        {"role": "user", "content": "Hello"}
    ]
)

print(response["message"]["content"])

ResponseError: an error was encountered while running the model: error: task id = 0, error: got exception: std::bad_alloc (status code: 500)

In [ ]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.device_count())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

True
1
NVIDIA GeForce RTX 3050 Laptop GPU

In [3]:
import torch
from transformers import AutoProcessor, AutoModelForImageTextToText

model_id = "HuggingFaceTB/SmolVLM-256M-Instruct"

processor = AutoProcessor.from_pretrained(model_id)

model = AutoModelForImageTextToText.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
).cuda()

print(next(model.parameters()).device)

d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

KeyboardInterrupt:

In [4]:
from ollama import chat

response = chat(
    model="qwen3.5:4b",
    messages=[
        {
            "role": "system",
            "content": "You are an expert text OCR reader. You will be given an image I want you to return its content as Markdown"
        },
        {
            "role": "user",
            "images": ["image.png"]
        }
      ],
    think=False
)

print(response["message"]["content"])

ResponseError: llama-server startup failed before projector CPU offload retry: llama-server reported out-of-memory during startup: ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer of size 774313984
alloc_tensor_range: failed to allocate CPU buffer of size 774313984
GGML_ASSERT(buffer); error stopping failed process: TerminateProcess: Access is denied. (status code: 500)

In [8]:
!pip install pymupdf

Requirement already satisfied: pymupdf in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (1.28.0)

In [9]:
import fitz
import os

pdf_path = "1_README.pdf" 
output_folder = "pages"

os.makedirs(output_folder, exist_ok=True)

doc = fitz.open(pdf_path)

for page_number in range(len(doc)):
    page = doc[page_number]

    pix = page.get_pixmap(dpi=300)

    image_path = os.path.join(
        output_folder,
        f"page_{page_number + 1}.png"
    )

    pix.save(image_path)

    print(f"Saved: {image_path}")

doc.close()

Saved: pages\page_1.png
Saved: pages\page_2.png
Saved: pages\page_3.png

In [10]:
!pip install ollama

Requirement already satisfied: ollama in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (0.6.2)
Requirement already satisfied: httpx>=0.27 in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from ollama) (2.13.4)
Requirement already satisfied: anyio in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from httpx>=0.27->ollama) (4.14.2)
Requirement already satisfied: certifi in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from httpx>=0.27->ollama) (2026.6.17)
Requirement already satisfied: httpcore==1.* in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from httpx>=0.27->ollama) (3.18)
Requirement already satisfied: h11>=0.16 in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from pydantic>=2.9->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from pydantic>=2.9->ollama) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from pydantic>=2.9->ollama) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in D:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from pydantic>=2.9->ollama) (0.4.2)

In [ ]:
from ollama import chat

response = chat(
    model="qwen3.5:4b",
    messages=[
        {
            "role": "system",
            "content": """
You are an OCR engine.
Extract all text from the image exactly.
Return only Markdown.
Do not summarize.
Do not stop until you finish the whole page.
"""
        },
        {
            "role": "user",
            "images": ["pages/page_1.png"]
        }
    ],
    options={
        "num_ctx": 16384,
        "num_predict": -1
    },
    think=False
)

print(response["message"]["content"])

In [1]:
from ollama import chat
import os

images_folder = "pages"
output_file = "document.md"

markdown_content = ""

images = sorted(os.listdir(images_folder))

for image in images:
    image_path = os.path.join(images_folder, image)

    print(f"Processing {image}...")

    response = chat(
        model="qwen3.5:4b",
        messages=[
            {
                "role": "system",
                "content": """
You are an OCR engine.
Extract all text from the image exactly.
Return only Markdown.
Do not summarize.
Do not stop until you finish the whole page.
"""
            },
            {
                "role": "user",
                "images": [image_path]
            }
        ],
        options={
            "num_ctx": 16384,
            "num_predict": -1
        },
        think=False
    )

    page_markdown = response["message"]["content"]

    markdown_content += f"\n\n<!-- {image} -->\n\n"
    markdown_content += page_markdown


with open(output_file, "w", encoding="utf-8") as f:
    f.write(markdown_content)


print("Done! Saved:", output_file)

Processing page_1.png...
Processing page_2.png...
Processing page_3.png...
Done! Saved: document.md

In [2]:
pip install datasets huggingface_hub

Requirement already satisfied: datasets in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (5.0.0)
Requirement already satisfied: huggingface_hub in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (1.24.0)
Requirement already satisfied: filelock in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (3.32.0)
Requirement already satisfied: numpy>=1.17 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=21.0.0 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (2.1.4)
Requirement already satisfied: requests>=2.32.2 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (4.69.0)
Requirement already satisfied: xxhash in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2026.4.0)
Requirement already satisfied: packaging in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from huggingface_hub) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from huggingface_hub) (1.5.2)
Requirement already satisfied: typing-extensions>=4.1.0 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: colorama in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface_hub) (0.4.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.2)
Requirement already satisfied: anyio in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from httpx<1.0.0->datasets) (2026.6.17)
Requirement already satisfied: httpcore==1.* in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.5)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: tzdata>=2022.1 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: six>=1.5 in d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
from datasets import load_dataset

dataset = load_dataset("v1v1d/v1v1d_docmatix_test_v1_fast")

print(dataset)

d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

DatasetDict({
    train: Dataset({
        features: ['id', 'image', 'pdf_name', 'page_number', 'page_size', 'layout', 'content_list', 'middle', 'model', 'markdown', 'html', 'html_with_coordinates', 'html_compact', 'raw_md', 'lines', 'images', 'equations', 'tables', 'pdf_info', 'vqa'],
        num_rows: 1500
    })
})

In [2]:
sample = dataset["train"][0]

print(sample)

{'id': '00006_page_0000', 'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1993x2579 at 0x132970C0C90>, 'pdf_name': '00006', 'page_number': 0, 'page_size': [956, 1237], 'layout': [{'type': 'title', 'coordinates': [166, 215, 867, 288], 'content': 'PUZZLE MADNESS', 'index': 0}, {'type': 'text', 'coordinates': [121, 325, 900, 355], 'content': 'Daily Medium Mathdoku Puzzle for Friday 18th June 2021', 'index': 1}, {'type': 'image_body', 'coordinates': [322, 382, 701, 675], 'content': '', 'index': 2}, {'type': 'discarded', 'coordinates': [432, 76, 598, 202], 'content': '', 'index': 3}], 'content_list': '[{"type": "text", "text": "PUZZLE MADNESS ", "text_level": 1, "page_idx": 0}, {"type": "text", "text": "Daily Medium Mathdoku Puzzle for Friday 18th June 2021 ", "page_idx": 0}, {"type": "image", "img_path": "images/11494ec3b1bce232bc8b9e151013523734d29142cd27657caeeb5ce3cfe5128a.jpg", "img_caption": [], "img_footnote": [], "page_idx": 0}]', 'middle': '{"preproc_blocks": [{"type": "title", "bbox": [155, 260, 810, 348], "lines": [{"bbox": [157, 264, 809, 352], "spans": [{"bbox": [157, 264, 809, 352], "score": 0.9, "content": "PUZZLE MADNESS", "type": "text"}], "index": 0}], "index": 0}, {"type": "text", "bbox": [113, 393, 841, 430], "lines": [{"bbox": [118, 402, 838, 431], "spans": [{"bbox": [118, 402, 838, 431], "score": 0.98, "content": "Daily Medium Mathdoku Puzzle for Friday 18th June 2021", "type": "text"}], "index": 1}], "index": 1}, {"type": "image", "bbox": [301, 462, 655, 816], "blocks": [{"type": "image_body", "bbox": [301, 462, 655, 816], "group_id": 0, "lines": [{"bbox": [301, 462, 655, 816], "spans": [{"bbox": [301, 462, 655, 816], "score": 0.661, "type": "image", "image_path": "11494ec3b1bce232bc8b9e151013523734d29142cd27657caeeb5ce3cfe5128a.jpg"}]}], "index": 5, "virtual_lines": [{"bbox": [301, 462, 655, 520.5], "spans": [], "index": 2}, {"bbox": [301, 520.5, 655, 579.0], "spans": [], "index": 3}, {"bbox": [301, 579.0, 655, 637.5], "spans": [], "index": 4}, {"bbox": [301, 637.5, 655, 696.0], "spans": [], "index": 5}, {"bbox": [301, 696.0, 655, 754.5], "spans": [], "index": 6}, {"bbox": [301, 754.5, 655, 813.0], "spans": [], "index": 7}, {"bbox": [301, 813.0, 655, 871.5], "spans": [], "index": 8}]}], "index": 5}], "layout_bboxes": [], "page_idx": 0, "page_size": [956.25, 1237.5], "_layout_tree": [], "images": [{"type": "image", "bbox": [301, 462, 655, 816], "blocks": [{"type": "image_body", "bbox": [301, 462, 655, 816], "group_id": 0, "lines": [{"bbox": [301, 462, 655, 816], "spans": [{"bbox": [301, 462, 655, 816], "score": 0.661, "type": "image", "image_path": "11494ec3b1bce232bc8b9e151013523734d29142cd27657caeeb5ce3cfe5128a.jpg"}]}], "index": 5, "virtual_lines": [{"bbox": [301, 462, 655, 520.5], "spans": [], "index": 2}, {"bbox": [301, 520.5, 655, 579.0], "spans": [], "index": 3}, {"bbox": [301, 579.0, 655, 637.5], "spans": [], "index": 4}, {"bbox": [301, 637.5, 655, 696.0], "spans": [], "index": 5}, {"bbox": [301, 696.0, 655, 754.5], "spans": [], "index": 6}, {"bbox": [301, 754.5, 655, 813.0], "spans": [], "index": 7}, {"bbox": [301, 813.0, 655, 871.5], "spans": [], "index": 8}]}], "index": 5}], "tables": [], "interline_equations": [], "discarded_blocks": [{"type": "discarded", "bbox": [404, 92, 559, 245], "lines": []}], "need_drop": false, "drop_reason": [], "para_blocks": [{"type": "title", "bbox": [155, 260, 810, 348], "lines": [{"bbox": [157, 264, 809, 352], "spans": [{"bbox": [157, 264, 809, 352], "score": 0.9, "content": "PUZZLE MADNESS", "type": "text"}], "index": 0}], "index": 0, "page_num": "page_0", "page_size": [956.25, 1237.5]}, {"type": "text", "bbox": [113, 393, 841, 430], "lines": [{"bbox": [118, 402, 838, 431], "spans": [{"bbox": [118, 402, 838, 431], "score": 0.98, "content": "Daily Medium Mathdoku Puzzle for Friday 18th June 2021", "type": "text"}], "index": 1}], "index": 1, "page_num": "page_0", "page_size": [956.25, 1237.5], "bbox_fs": [118, 402, 838, 431]}, {"type": "image", "bbox": [301, 462, 655, 816], "blocks": [{"type": "image_body", "bbox": [301, 462, 655, 816], "group_id": 0, "lines": [{"bbox": [301, 462, 655, 816], "spans": [{"bbox": [301, 462, 655, 816], "score": 0.661, "type": "image", "image_path": "11494ec3b1bce232bc8b9e151013523734d29142cd27657caeeb5ce3cfe5128a.jpg"}]}], "index": 5, "virtual_lines": [{"bbox": [301, 462, 655, 520.5], "spans": [], "index": 2}, {"bbox": [301, 520.5, 655, 579.0], "spans": [], "index": 3}, {"bbox": [301, 579.0, 655, 637.5], "spans": [], "index": 4}, {"bbox": [301, 637.5, 655, 696.0], "spans": [], "index": 5}, {"bbox": [301, 696.0, 655, 754.5], "spans": [], "index": 6}, {"bbox": [301, 754.5, 655, 813.0], "spans": [], "index": 7}, {"bbox": [301, 813.0, 655, 871.5], "spans": [], "index": 8}]}], "index": 5, "page_num": "page_0", "page_size": [956.25, 1237.5]}]}', 'model': '{"layout_dets": [{"category_id": 1, "poly": [314, 1093, 2337, 1093, 2337, 1195, 314, 1195], "score": 0.866}, {"category_id": 3, "poly": [837, 1284, 1820, 1284, 1820, 2268, 837, 2268], "score": 0.661}, {"category_id": 0, "poly": [433, 724, 2249, 724, 2249, 969, 433, 969], "score": 0.601}, {"category_id": 2, "poly": [1122, 257, 1552, 257, 1552, 682, 1122, 682], "score": 0.343}, {"category_id": 5, "poly": [837, 1284, 1820, 1284, 1820, 2268, 837, 2268], "score": 0.263, "html": "<html><body><table><tr><td>10+</td><td></td><td></td><td>2/</td><td></td><td>3-</td></tr><tr><td>+6</td><td></td><td>3/</td><td>3/</td><td></td><td></td></tr><tr><td>5-</td><td>5+</td><td></td><td>14+</td><td></td><td></td></tr><tr><td></td><td></td><td>15*</td><td>+6</td><td>8*</td><td></td></tr><tr><td>1-</td><td></td><td></td><td></td><td>13+</td><td></td></tr><tr><td>3-</td><td></td><td>12*</td><td></td><td></td><td></td></tr></table></body></html>"}, {"category_id": 15, "poly": [330.0, 1119.0, 2327.0, 1119.0, 2327.0, 1197.0, 330.0, 1197.0], "score": 0.98, "text": "Daily Medium Mathdoku Puzzle for Friday 18th June 2021"}, {"category_id": 15, "poly": [436.0, 734.0, 2248.0, 734.0, 2248.0, 979.0, 436.0, 979.0], "score": 0.9, "text": "PUZZLE MADNESS"}], "page_info": {"page_no": 0, "height": 3438, "width": 2657}}', 'markdown': '# PUZZLE MADNESS\n\nDaily Medium Mathdoku Puzzle for Friday 18th June 2021\n\n![img_1](322,382,701,675)\n\n![img_2](322,382,701,675)\n', 'html': '<div class="pdf-page">\n<h1>PUZZLE MADNESS</h1>\n<p>Daily Medium Mathdoku Puzzle for Friday 18th June 2021</p>\n<figure><img data-bbox="322,382,701,675" />\n</figure>\n<figure><img data-bbox="322,382,701,675" />\n</figure>\n</div>', 'html_with_coordinates': '<div class="pdf-page">\n<h1 class="pdf-title" data-x="166" data-y="215" data-width="701" data-height="73">PUZZLE MADNESS</h1>\n<p class="pdf-text" data-x="121" data-y="325" data-width="779" data-height="30">Daily Medium Mathdoku Puzzle for Friday 18th June 2021</p>\n<figure class="pdf-image" data-x="322" data-y="382" data-width="379" data-height="293"><img data-bbox="322,382,701,675" />\n</figure>\n<figure class="pdf-image" data-x="322" data-y="382" data-width="379" data-height="293"><img data-bbox="322,382,701,675" />\n</figure>\n</div>', 'html_compact': '<div class="page">\n<h1 class="title" bbox="166,215,701,73">PUZZLE MADNESS</h1>\n<p class="text" bbox="121,325,779,30">Daily Medium Mathdoku Puzzle for Friday 18th June 2021</p>\n<figure class="image" bbox="322,382,379,293"></figure>\n<figure class="image" bbox="322,382,379,293"></figure>\n</div>', 'raw_md': '# PUZZLE MADNESS  \n\nDaily Medium Mathdoku Puzzle for Friday 18th June 2021  \n\n![img_1](322,382,701,675)', 'lines': '[{"type": "text", "coordinates": [168, 218, 866, 291], "content": "PUZZLE MADNESS", "index": 0}, {"type": "text", "coordinates": [126, 332, 897, 356], "content": "Daily Medium Mathdoku Puzzle for Friday 18th June 2021", "index": 1}, {"type": "text", "coordinates": [322, 382, 701, 675], "content": "", "index": 2}]', 'images': '[{"coordinates": [322, 382, 701, 675], "index": 0, "caption": "", "caption_coordinates": [0, 0, 0, 0]}, {"coordinates": [322, 382, 701, 675], "index": 1, "caption": "", "caption_coordinates": [0, 0, 0, 0]}]', 'equations': '[]', 'tables': '[]', 'pdf_info': '{"document_info": {"total_pages": 15, "parse_type": "ocr", "version": "1.0.1", "total_content_list_items": 113}, "content_statistics": {"total_blocks": 144, "total_lines": 388, "total_images": 10, "total_equations": 0, "total_tables": 9, "total_characters": 19075, "total_words": 2713, "block_type_distribution": {"title": 23, "text": 62, "image_body": 5, "discarded": 30, "list": 19, "table_body": 4, "table_caption": 1}}, "model_statistics": {"total_layout_detections": 687, "avg_confidence": 0.8940727802037883, "min_confidence": 0.255, "max_confidence": 1.0}}', 'vqa': [{'user': 'What is the title and date of the math puzzle in the text?', 'assistant': 'The title of the math puzzle is "Daily Medium Mathdoku Puzzle" and it is dated for Friday, 18th June 2021.', 'source': 'PDFA key: 228240'}, {'user': 'How many rows of calculations are listed in the puzzle?', 'assistant': 'There are six rows of calculations listed in the puzzle.', 'source': 'PDFA key: 228240'}, {'user': 'What operations are included in the first row of the puzzle?', 'assistant': 'The operations in the first row are addition and subtraction.', 'source': 'PDFA key: 228240'}, {'user': 'Which row includes multiplication in the puzzle?', 'assistant': 'The fifth row includes multiplication in the puzzle.', 'source': 'PDFA key: 228240'}, {'user': 'How many numbers are present in the second row of the puzzle?', 'assistant': 'There are five numbers present in the second row of the puzzle.', 'source': 'PDFA key: 228240'}, {'user': 'What is the maximum number of operations in a single row in the puzzle?', 'assistant': 'The maximum number of operations in a single row in the puzzle is five.', 'source': 'PDFA key: 228240'}, {'user': 'What is the common characteristic of all the rows in the puzzle?', 'assistant': 'Every row in the puzzle consists of a set of numbers with one operation symbol between each pair of numbers.', 'source': 'PDFA key: 228240'}, {'user': 'In which row is the number 1 used?', 'assistant': 'The number 1 is used in the sixth row of the puzzle.', 'source': 'PDFA key: 228240'}, {'user': 'Which row contains the largest number in the puzzle?', 'assistant': 'The fifth row contains the largest number (15) in the puzzle.', 'source': 'PDFA key: 228240'}]}

In [3]:
for key, value in sample.items():
    print("=" * 50)
    print(key)
    print(type(value))

==================================================
id
<class 'str'>
==================================================
image
<class 'PIL.PngImagePlugin.PngImageFile'>
==================================================
pdf_name
<class 'str'>
==================================================
page_number
<class 'int'>
==================================================
page_size
<class 'list'>
==================================================
layout
<class 'list'>
==================================================
content_list
<class 'str'>
==================================================
middle
<class 'str'>
==================================================
model
<class 'str'>
==================================================
markdown
<class 'str'>
==================================================
html
<class 'str'>
==================================================
html_with_coordinates
<class 'str'>
==================================================
html_compact
<class 'str'>
==================================================
raw_md
<class 'str'>
==================================================
lines
<class 'str'>
==================================================
images
<class 'str'>
==================================================
equations
<class 'str'>
==================================================
tables
<class 'str'>
==================================================
pdf_info
<class 'str'>
==================================================
vqa
<class 'list'>

In [4]:
sample = dataset["train"][1233]

print(sample["raw_md"])

# 12 Dust Control

ust controls may be needed on industrial sites for various reasons, including land disturbance, demolition and material handling areas. If effective, dust controls can prevent pollutants from contaminating stormwater runoff by reducing the surface and air transport of dust caused by these activities.

# Practices to ControlDustfrom Land Disturbances and DemolitionActivities

$\Cup$ Use temporary controls, such as palliatives or chemical soil treatments, that are applied as sprayon adhesives. Common palliatives include:

$\nu$ Calcium Chloride
$\nu$ Ammoniac Asphalt Emulsion
VLatexEmulsion
$\nu$ Resin-Water Emulsion
VLignin

$\circleddash$ Since certain chemicals may be inappropriate for some soil types or application areas, the permittee should check with the City and Department of Environmental Quality (DEQ) prior to the application of chemical treatments. Vehiclesshouldnotbe driven over the treated area to avoid the tracking of the chemicals to other areas on or off the site. In addition, irrigation is a temporary measure involving a light application of water to moisten the soil surface. The minimum amount of water should be applied because an excess of water can cause erosion.

· Pave or rock traffic ways to prevent dust. · Geotextile fabric should be used under gravel or rock to prevent it from sinking into the mud. · Industrial areas should be paved or vegetated.

![img_1](546,163,966,316)

soil exposure by temporary or permanent soil stabilization controls, such as:

Mulching
/Seeding
$\nu$ Spreading coarse gravel or crushed stone
$\nu$ Planting trees

$\mathbf{\^{ep}}$ Install temporary or permanent windbreaks or barriers that reduce airborne particles by slowing wind velocities and causing particles to drop. Large trees and shrubs left in place can provide wind barriers, while temporary measures include solid board fence, tarp curtains, sediment walls, crate walls and bales of hay.

$\circledcirc$ Inspect sites requiring dust controls frequently and reapply materials or controls as needed.

# PracticestoControlDustfromMaterial HandlingProcessandTransferAreas

$\oplus$ Install dust collection systems, such as negative pressure systems (vacuum systems), collector systems (bag and cyclone) or filter systems. $\circleddash$ Use street sweepers to collect dust. The vacuum type are more efficient and are most effective on dry areas. Brush sweepers can also be used. $\circledast$ Train employees in the proper operation of equipment according to themanufacturers'recommendations and inspect the equipment regularly.

In [5]:
print(sample["markdown"])

# 12 Dust Control

![img_1](546,163,966,316)

![img_2](546,163,966,316)

ust controls may be needed on industrial sites for various reasons, including land distur- bance, demolition and material handling areas. If effective, dust controls can prevent pollutants from contaminating stormwater runoff by reducing the surface and air transport of dust caused by these activities.

soil exposure by temporary or permanent soil sta- bilization controls, such as:

# Practices to ControlDustfrom Land Disturbances and DemolitionActivities

- Mulching /Seeding $\nu$ Spreading coarse gravel or crushed stone $\nu$ Planting trees

$\Cup$ Use temporary controls, such as palliatives or chemical soil treatments, that are applied as spray- on adhesives. Common palliatives include:

$\mathbf{\^{ep}}$  Install temporary or permanent windbreaks or barriers that reduce airborne particles by slowing wind velocities and causing particles to drop. Large trees and shrubs left in place can provide wind barriers, while temporary measures include solid board fence, tarp curtains, sediment walls, crate walls and bales of hay.

- $\nu$ Calcium Chloride $\nu$ Ammoniac Asphalt Emulsion VLatexEmulsion $\nu$ Resin-Water Emulsion VLignin

$\circleddash$ Since certain chemicals may be inappropriate for some soil types or application areas, the permittee should check with the City and Department of Environmental Quality (DEQ) prior to the application of chemical treatments. Vehiclesshouldnotbe driven over the treated area to avoid the tracking of the chemicals to other areas on or off the site. In addition, irrigation is a temporary measure involving a light application of water to moisten the soil surface. The minimum amount of water should be applied because an excess of water can cause erosion.

$\circledcirc$ Inspect sites requiring dust controls frequently and reapply materials or controls as needed.

# PracticestoControlDustfromMaterial HandlingProcessandTransferAreas

$\oplus$ Install dust collection systems, such as negative pressure systems (vacuum systems), collector sys- tems (bag and cyclone) or filter systems. $\circleddash$ Use street sweepers to collect dust. The vacuum type are more efficient and are most effective on dry areas. Brush sweepers can also be used. $\circledast$ Train employees in the proper operation of equipment according to themanufacturers'recom- mendations and inspect the equipment regularly.

· Pave or rock traffic ways to prevent dust. · Geotextile fabric should be used under gravel or rock to prevent it from sinking into the mud. · Industrial areas should be paved or vegetated.

In [6]:
sample = dataset["train"][0]

sample["image"].save("test.png")

with open("test.md", "w", encoding="utf-8") as f:
    f.write(sample["markdown"])

print("Done")

Done

In [7]:
print(len(dataset["train"]))

1500

In [8]:
small_dataset = dataset["train"].select(range(10))

def preprocess(example):
    return {
        "image": example["image"],
        "prompt": "Convert this document to Markdown.",
        "answer": example["markdown"]
    }

train_dataset = small_dataset.map(
    preprocess,
    remove_columns=small_dataset.column_names
)

print(train_dataset)

Dataset({
    features: ['image', 'prompt', 'answer'],
    num_rows: 10
})

In [9]:
print(train_dataset[0]["prompt"])
print("=" * 50)
print(train_dataset[0]["answer"][:500])

Convert this document to Markdown.
==================================================
# PUZZLE MADNESS

Daily Medium Mathdoku Puzzle for Friday 18th June 2021

![img_1](322,382,701,675)

![img_2](322,382,701,675)

In [ ]:
from IPython.display import display

display(train_dataset[0]["image"])

In [11]:
import torch

print(torch.__version__)
print(torch.version.cuda)

2.6.0+cu124
12.4

In [12]:
import torch

print(torch.cuda.is_available())

if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 3050 Laptop GPU

In [9]:
import transformers
import peft
import trl

print(transformers.__version__)
print(peft.__version__)
print(trl.__version__)

5.14.1
0.19.1
1.9.0

In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.6.0+cu124
True
NVIDIA GeForce RTX 3050 Laptop GPU

In [3]:
import torch
from transformers import AutoProcessor, AutoModelForImageTextToText

model_id = "HuggingFaceTB/SmolVLM-256M-Instruct"

processor = AutoProcessor.from_pretrained(model_id)

model = AutoModelForImageTextToText.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="cuda"
)

print("Model Loaded")

Loading weights: 100%|██████████| 471/471 [00:00<00:00, 995.53it/s]

Model Loaded

In [4]:
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    target_modules="all-linear",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

trainable params: 7,744,512 || all params: 264,229,440 || trainable%: 2.9310

In [6]:
from datasets import load_dataset

dataset = load_dataset("v1v1d/v1v1d_docmatix_test_v1_fast")

print(dataset)
print(dataset["train"][0].keys())

DatasetDict({
    train: Dataset({
        features: ['id', 'image', 'pdf_name', 'page_number', 'page_size', 'layout', 'content_list', 'middle', 'model', 'markdown', 'html', 'html_with_coordinates', 'html_compact', 'raw_md', 'lines', 'images', 'equations', 'tables', 'pdf_info', 'vqa'],
        num_rows: 1500
    })
})
dict_keys(['id', 'image', 'pdf_name', 'page_number', 'page_size', 'layout', 'content_list', 'middle', 'model', 'markdown', 'html', 'html_with_coordinates', 'html_compact', 'raw_md', 'lines', 'images', 'equations', 'tables', 'pdf_info', 'vqa'])

In [10]:
train_dataset = dataset["train"].select(range(150))

def format_example(example):
    return {
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "image"},
                    {
                        "type": "text",
                        "text": "Convert this document image to Markdown."
                    }
                ]
            },
            {
                "role": "assistant",
                "content": [
                    {
                        "type": "text",
                        "text": example["markdown"]
                    }
                ]
            }
        ],
        "image": example["image"]
    }

train_dataset = train_dataset.map(
    format_example,
    remove_columns=train_dataset.column_names
)

In [11]:
print(train_dataset[0])

{'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1993x2579 at 0x19AE7F2AB50>, 'messages': [{'role': 'user', 'content': [{'type': 'image'}, {'type': 'text', 'text': 'Convert this document image to Markdown.'}]}, {'role': 'assistant', 'content': [{'type': 'text', 'text': '# PUZZLE MADNESS\n\nDaily Medium Mathdoku Puzzle for Friday 18th June 2021\n\n![img_1](322,382,701,675)\n\n![img_2](322,382,701,675)\n'}]}]}

In [12]:
from PIL import Image

IGNORE_INDEX = -100

def collate_fn(examples):

    texts = []
    images = []

    for example in examples:

        text = processor.apply_chat_template(
            example["messages"],
            tokenize=False,
            add_generation_prompt=False,
        )

        texts.append(text)
        images.append(example["image"])

    batch = processor(
        text=texts,
        images=images,
        padding=True,
        return_tensors="pt",
    )

    labels = batch["input_ids"].clone()

    assistant_token_ids = processor.tokenizer.encode(
        "Assistant:",
        add_special_tokens=False
    )

    for i in range(labels.size(0)):

        ids = labels[i].tolist()

        start = None

        for j in range(len(ids) - len(assistant_token_ids)):
            if ids[j:j+len(assistant_token_ids)] == assistant_token_ids:
                start = j + len(assistant_token_ids)
                break

        if start is None:
            labels[i][:] = IGNORE_INDEX
        else:
            labels[i][:start] = IGNORE_INDEX

        labels[i][labels[i] == processor.tokenizer.pad_token_id] = IGNORE_INDEX

    batch["labels"] = labels

    return batch

In [7]:
batch = collate_fn([train_dataset[0]])

print(processor.tokenizer.decode(batch["labels"][0][batch["labels"][0] != -100]))

 # PUZZLE MADNESS

Daily Medium Mathdoku Puzzle for Friday 18th June 2021

![img_1](322,382,701,675)

![img_2](322,382,701,675)
<end_of_utterance>

In [13]:
processor.image_processor.do_image_splitting = False

processor.image_processor.size = {
    "height": 384,
    "width": 384
}

In [14]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./smolvlm-ocr",

    # Batch
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,

    # Training
    num_train_epochs=2,
    learning_rate=2e-4,

    # Memory
    fp16=True,
    gradient_checkpointing=True,

    # Logging
    logging_steps=10,
    save_strategy="no",
    report_to="none",
    remove_unused_columns=False,

    # DataLoader
    dataloader_num_workers=0,
    dataloader_pin_memory=False,
)

In [15]:
from trl import SFTTrainer
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    processing_class=processor,
    data_collator=collate_fn,
)

In [16]:
print(model)
print(processor)

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Idefics3ForConditionalGeneration(
      (model): Idefics3Model(
        (vision_model): Idefics3VisionTransformer(
          (embeddings): Idefics3VisionEmbeddings(
            (patch_embedding): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16), padding=valid)
            (position_embedding): Embedding(1024, 768)
          )
          (encoder): Idefics3Encoder(
            (layers): ModuleList(
              (0-11): 12 x Idefics3EncoderLayer(
                (self_attn): Idefics3VisionAttention(
                  (k_proj): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (v_proj): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (q_proj): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (out_proj): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                )
                (layer_norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
                (mlp): Idefics3VisionMLP(
                  (activation_fn): GELUTanh()
                  (fc1): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=3072, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=3072, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (fc2): lora.Linear(
                    (base_layer): Linear(in_features=3072, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=3072, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                )
                (layer_norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
              )
            )
          )
          (post_layernorm): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        )
        (connector): Idefics3Connector(
          (modality_projection): Idefics3SimpleMLP(
            (proj): lora.Linear(
              (base_layer): Linear(in_features=12288, out_features=576, bias=False)
              (lora_dropout): ModuleDict(
                (default): Dropout(p=0.05, inplace=False)
              )
              (lora_A): ModuleDict(
                (default): Linear(in_features=12288, out_features=16, bias=False)
              )
              (lora_B): ModuleDict(
                (default): Linear(in_features=16, out_features=576, bias=False)
              )
              (lora_embedding_A): ParameterDict()
              (lora_embedding_B): ParameterDict()
              (lora_magnitude_vector): ModuleDict()
            )
          )
        )
        (text_model): LlamaModel(
          (embed_tokens): Embedding(49280, 576, padding_idx=2)
          (layers): ModuleList(
            (0-29): 30 x LlamaDecoderLayer(
              (self_attn): LlamaAttention(
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=576, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=576, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (k_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=192, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=192, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=192, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=192, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (o_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=576, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=576, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (mlp): LlamaMLP(
                (gate_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=1536, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1536, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (up_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=1536, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1536, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (down_proj): lora.Linear(
                  (base_layer): Linear(in_features=1536, out_features=576, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1536, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=576, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (act_fn): SiLUActivation()
              )
              (input_layernorm): LlamaRMSNorm((576,), eps=1e-05)
              (post_attention_layernorm): LlamaRMSNorm((576,), eps=1e-05)
            )
          )
          (norm): LlamaRMSNorm((576,), eps=1e-05)
          (rotary_emb): LlamaRotaryEmbedding()
        )
      )
      (lm_head): Linear(in_features=576, out_features=49280, bias=False)
    )
  )
)
Idefics3Processor:
- image_processor: Idefics3ImageProcessorPil {
  "do_convert_rgb": true,
  "do_image_splitting": false,
  "do_normalize": true,
  "do_pad": true,
  "do_rescale": true,
  "do_resize": true,
  "image_mean": [
    0.5,
    0.5,
    0.5
  ],
  "image_processor_type": "Idefics3ImageProcessor",
  "image_std": [
    0.5,
    0.5,
    0.5
  ],
  "max_image_size": {
    "longest_edge": 512
  },
  "resample": 1,
  "rescale_factor": 0.00392156862745098,
  "size": {
    "height": 384,
    "width": 384
  }
}

- tokenizer: GPT2Tokenizer(name_or_path='HuggingFaceTB/SmolVLM-256M-Instruct', vocab_size=49152, model_max_length=8192, padding_side='right', truncation_side='left', special_tokens={'bos_token': '<|im_start|>', 'eos_token': '<end_of_utterance>', 'unk_token': '<|endoftext|>', 'pad_token': '<|im_end|>'}, added_tokens_decoder={
	0: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("<|im_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("<|im_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("<repo_name>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("<reponame>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	5: AddedToken("<file_sep>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	6: AddedToken("<filename>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	7: AddedToken("<gh_stars>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	8: AddedToken("<issue_start>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	9: AddedToken("<issue_comment>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	10: AddedToken("<issue_closed>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	11: AddedToken("<jupyter_start>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	12: AddedToken("<jupyter_text>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	13: AddedToken("<jupyter_code>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	14: AddedToken("<jupyter_output>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	15: AddedToken("<jupyter_script>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	16: AddedToken("<empty_output>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49152: AddedToken("<global-img>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49153: AddedToken("<row_1_col_1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49154: AddedToken("<row_1_col_2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49155: AddedToken("<row_1_col_3>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49156: AddedToken("<row_1_col_4>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49157: AddedToken("<row_1_col_5>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49158: AddedToken("<row_1_col_6>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49159: AddedToken("<row_2_col_1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49160: AddedToken("<row_2_col_2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49161: AddedToken("<row_2_col_3>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49162: AddedToken("<row_2_col_4>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49163: AddedToken("<row_2_col_5>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49164: AddedToken("<row_2_col_6>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49165: AddedToken("<row_3_col_1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49166: AddedToken("<row_3_col_2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49167: AddedToken("<row_3_col_3>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49168: AddedToken("<row_3_col_4>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49169: AddedToken("<row_3_col_5>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49170: AddedToken("<row_3_col_6>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49171: AddedToken("<row_4_col_1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49172: AddedToken("<row_4_col_2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49173: AddedToken("<row_4_col_3>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49174: AddedToken("<row_4_col_4>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49175: AddedToken("<row_4_col_5>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49176: AddedToken("<row_4_col_6>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49177: AddedToken("<row_5_col_1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49178: AddedToken("<row_5_col_2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49179: AddedToken("<row_5_col_3>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49180: AddedToken("<row_5_col_4>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49181: AddedToken("<row_5_col_5>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49182: AddedToken("<row_5_col_6>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49183: AddedToken("<row_6_col_1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49184: AddedToken("<row_6_col_2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49185: AddedToken("<row_6_col_3>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49186: AddedToken("<row_6_col_4>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49187: AddedToken("<row_6_col_5>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49188: AddedToken("<row_6_col_6>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49189: AddedToken("<fake_token_around_image>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49190: AddedToken("<image>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49191: AddedToken("<|reserved_special_token_0|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49192: AddedToken("<|reserved_special_token_1|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49193: AddedToken("<|reserved_special_token_2|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49194: AddedToken("<|reserved_special_token_3|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49195: AddedToken("<|reserved_special_token_4|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),

In [17]:
print(len(train_dataset))
print(train_dataset[0].keys())

150
dict_keys(['image', 'messages'])

In [18]:
from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    processing_class=processor,
    data_collator=collate_fn,
)

print("Trainer Ready")

Trainer Ready

In [19]:
trainer.train()

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 49279, 'bos_token_id': 1, 'pad_token_id': 2}.

TrainOutput(global_step=38, training_loss=2.632912886770148, metrics={'train_runtime': 295.9105, 'train_samples_per_second': 1.014, 'train_steps_per_second': 0.128, 'total_flos': 229184105492736.0, 'train_loss': 2.632912886770148, 'entropy': 2.446228584935588, 'num_tokens': 162502.0, 'mean_token_accuracy': 0.5547224206309165, 'epoch': 2.0})

In [20]:
model.save_pretrained("./smolvlm-ocr-lora")
processor.save_pretrained("./smolvlm-ocr-lora")

['./smolvlm-ocr-lora\\processor_config.json']

In [21]:
image = train_dataset[0]["image"]

In [24]:
import torch

# خلي الموديل في وضع التقييم
model.eval()

# أول صورة من الـ dataset
image = train_dataset[0]["image"]

messages = [
    {
        "role": "user",
        "content": [
            {"type": "image", "image": image},
            {
                "type": "text",
                "text": "Convert this document image to Markdown."
            }
        ]
    }
]

# إنشاء الـ Prompt
prompt = processor.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

# تجهيز الـ Inputs
inputs = processor(
    text=prompt,
    images=[image],
    return_tensors="pt"
).to(model.device)

# توليد الإجابة
with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        do_sample=False,
        repetition_penalty=1.1,
        early_stopping=True,
        eos_token_id=processor.tokenizer.eos_token_id,
    )

# حذف الـ Prompt والإبقاء على الإجابة فقط
generated_ids = outputs[:, inputs["input_ids"].shape[1]:]

prediction = processor.batch_decode(
    generated_ids,
    skip_special_tokens=True
)[0]

print("=" * 80)
print("Prediction:")
print(prediction)

print("\n" + "=" * 80)
print("Ground Truth:")
print(train_dataset[0]["messages"][1]["content"][0]["text"])

[transformers] The following generation flags are not valid and may be ignored: ['early_stopping']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

================================================================================
Prediction:
 PUZZLEMADNESS
Daily Medium MathodokuPuzzle for Friday 18th June2021

#PUZZLEMADNESS

##

###

####

**PUZZLEMADNESS**

- **Daily Medium Mathodoku Puzzle for Friday 18th June2021**

---

The Daily Medium Mathodoku Puzzle is a puzzle that involves solving a math problem using the

================================================================================
Ground Truth:
# PUZZLE MADNESS

Daily Medium Mathdoku Puzzle for Friday 18th June 2021

![img_1](322,382,701,675)

![img_2](322,382,701,675)

In [9]:
batch = collate_fn([train_dataset[0]])

for k, v in batch.items():
    print(k, v.shape)

input_ids torch.Size([1, 160])
attention_mask torch.Size([1, 160])
pixel_values torch.Size([1, 1, 3, 512, 512])
pixel_attention_mask torch.Size([1, 1, 512, 512])
labels torch.Size([1, 160])

In [10]:
print(processor.image_processor)

Idefics3ImageProcessorPil {
  "do_convert_rgb": true,
  "do_image_splitting": false,
  "do_normalize": true,
  "do_pad": true,
  "do_rescale": true,
  "do_resize": true,
  "image_mean": [
    0.5,
    0.5,
    0.5
  ],
  "image_processor_type": "Idefics3ImageProcessor",
  "image_std": [
    0.5,
    0.5,
    0.5
  ],
  "max_image_size": {
    "longest_edge": 512
  },
  "resample": 1,
  "rescale_factor": 0.00392156862745098,
  "size": {
    "height": 384,
    "width": 384
  }
}

In [7]:
from trl import SFTTrainer

print("TRL Ready")

TRL Ready

In [8]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./smolvlm-ocr",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    num_train_epochs=2,
    learning_rate=2e-4,
    logging_steps=5,
    save_strategy="no",
    fp16=True,
    gradient_checkpointing=True,
    remove_unused_columns=False,
    report_to="none"
)

print("TrainingArguments Updated")

TrainingArguments Updated

In [9]:
from PIL import Image
import io

def collate_fn(examples):

    texts = []
    images = []

    for example in examples:

        text = processor.apply_chat_template(
            example["messages"],
            tokenize=False,
            add_generation_prompt=False
        )

        texts.append(text)

        img = example["images"][0]

        if img["bytes"] is not None:
            image = Image.open(
                io.BytesIO(img["bytes"])
            ).convert("RGB")
        else:
            image = Image.open(
                img["path"]
            ).convert("RGB")

        images.append(image)


    batch = processor(
        text=texts,
        images=images,
        return_tensors="pt",
        padding=True
    )

    batch["labels"] = batch["input_ids"].clone()

    return batch

In [10]:
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    processing_class=processor,
    data_collator=collate_fn,
)

print("Trainer Updated")

Trainer Updated

In [11]:
trainer.train()

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 49279, 'bos_token_id': 1, 'pad_token_id': 2}.

TrainOutput(global_step=38, training_loss=4.190597753775747, metrics={'train_runtime': 1534.6118, 'train_samples_per_second': 0.195, 'train_steps_per_second': 0.025, 'total_flos': 617288860424448.0, 'train_loss': 4.190597753775747, 'entropy': 0.890768133781173, 'num_tokens': 437686.0, 'mean_token_accuracy': 0.8419012156399813, 'epoch': 2.0})

In [11]:
print(train_dataset)

Dataset({
    features: ['id', 'image', 'pdf_name', 'page_number', 'page_size', 'layout', 'content_list', 'middle', 'model', 'markdown', 'html', 'html_with_coordinates', 'html_compact', 'raw_md', 'lines', 'images', 'equations', 'tables', 'pdf_info', 'vqa', 'messages'],
    num_rows: 200
})

In [12]:
batch = collate_fn(
    [train_dataset[0]]
)

for k,v in batch.items():
    print(k, v.shape)

input_ids torch.Size([1, 1220])
attention_mask torch.Size([1, 1220])
pixel_values torch.Size([1, 17, 3, 512, 512])
pixel_attention_mask torch.Size([1, 17, 512, 512])
labels torch.Size([1, 1220])

In [13]:
batch = collate_fn([train_dataset[0]])

# نحط البيانات على نفس الجهاز بتاع الموديل
batch = {
    k: v.to(model.device)
    for k, v in batch.items()
}

with torch.no_grad():
    outputs = model(**batch)

print(outputs.loss)

tensor(0.2347, device='cuda:0')

In [14]:
model.print_trainable_parameters()

trainable params: 7,744,512 || all params: 264,229,440 || trainable%: 2.9310

In [15]:
model.save_pretrained("./smolvlm-ocr-lora")
processor.save_pretrained("./smolvlm-ocr-lora")

print("Model Saved")

Model Saved

In [ ]:
import torch
from transformers import AutoProcessor, AutoModelForImageTextToText
from peft import PeftModel

base_model_id = "HuggingFaceTB/SmolVLM-256M-Instruct"

processor = AutoProcessor.from_pretrained(base_model_id)

base_model = AutoModelForImageTextToText.from_pretrained(
    base_model_id,
    torch_dtype=torch.float16,
    device_map="cuda"
)

model = PeftModel.from_pretrained(
    base_model,
    "./smolvlm-ocr-lora"
)

model.eval()

print("Model Loaded")

Loading weights: 100%|██████████| 471/471 [00:00<00:00, 500.82it/s]

Model Loaded

In [19]:
import os

print(os.getcwd())

d:\OneDrive\Documents\GitHub\summer-intern-2026-02\Abdalah anwer

In [21]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith(".png"):
            print(os.path.join(root, file))

.\image-flower.png
.\image.png
.\test.png
.\pages\page_1.png
.\pages\page_2.png
.\pages\page_3.png

In [22]:
import io
from PIL import Image

example = train_dataset[0]
img = example["images"][0]

if img["bytes"] is not None:
    image = Image.open(io.BytesIO(img["bytes"])).convert("RGB")
else:
    image = Image.open(img["path"]).convert("RGB")
messages = [
    {
        "role": "user",
        "content": [
            {"type": "image", "image": image},
            {"type": "text", "text": "Convert this document to Markdown."}
        ]
    }
]

prompt = processor.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

inputs = processor(
    text=prompt,
    images=[image],
    return_tensors="pt"
).to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=512,
        do_sample=False,
        temperature=0.0,
        repetition_penalty=1.2,
        eos_token_id=processor.tokenizer.eos_token_id,
    )

generated_text = processor.decode(
    outputs[0][inputs["input_ids"].shape[1]:],
    skip_special_tokens=True
)

print(generated_text)

 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |

In [23]:
print(train_dataset[0]["messages"])
print(train_dataset[0]["images"])

[{'role': 'user', 'content': [{'type': 'image'}, {'type': 'text', 'text': 'Convert this document image to Markdown.'}]}, {'role': 'assistant', 'content': [{'type': 'text', 'text': '# PUZZLE MADNESS\n\nDaily Medium Mathdoku Puzzle for Friday 18th June 2021\n\n![img_1](322,382,701,675)\n\n![img_2](322,382,701,675)\n'}]}]

In [24]:
text = processor.apply_chat_template(
    train_dataset[0]["messages"],
    tokenize=False,
    add_generation_prompt=False
)

print(text)

<|im_start|>User:<image>Convert this document image to Markdown.<end_of_utterance>
Assistant: # PUZZLE MADNESS

Daily Medium Mathdoku Puzzle for Friday 18th June 2021

![img_1](322,382,701,675)

![img_2](322,382,701,675)
<end_of_utterance>

In [25]:
batch = collate_fn([train_dataset[0]])

print(processor.tokenizer.decode(batch["labels"][0]))

<|im_start|>User:<fake_token_around_image><row_1_col_1><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_1_col_2><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_1_col_3><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_1_col_4><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image>
<fake_token_around_image><row_2_col_1><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_2_col_2><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_2_col_3><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_2_col_4><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image>
<fake_token_around_image><row_3_col_1><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_3_col_2><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_3_col_3><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_3_col_4><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image>
<fake_token_around_image><row_4_col_1><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_4_col_2><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_4_col_3><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image><row_4_col_4><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image>

<fake_token_around_image><global-img><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><fake_token_around_image>Convert this document image to Markdown.<end_of_utterance>
Assistant: # PUZZLE MADNESS

Daily Medium Mathdoku Puzzle for Friday 18th June 2021

![img_1](322,382,701,675)

![img_2](322,382,701,675)
<end_of_utterance>

In [26]:
import transformers
import trl

print(transformers.__version__)
print(trl.__version__)

5.14.1
1.9.0

In [18]:
model = PeftModel.from_pretrained(
    base_model,
    "./smolvlm-ocr-lora"
)

d:\OneDrive\Documents\GitHub\summer-intern-2026-02\.venv\Lib\site-packages\peft\tuners\tuners_utils.py:302: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

In [20]:
print(type(model))
print(model)

<class 'peft.peft_model.PeftModelForCausalLM'>
PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Idefics3ForConditionalGeneration(
      (model): Idefics3Model(
        (vision_model): Idefics3VisionTransformer(
          (embeddings): Idefics3VisionEmbeddings(
            (patch_embedding): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16), padding=valid)
            (position_embedding): Embedding(1024, 768)
          )
          (encoder): Idefics3Encoder(
            (layers): ModuleList(
              (0-11): 12 x Idefics3EncoderLayer(
                (self_attn): Idefics3VisionAttention(
                  (k_proj): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (v_proj): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (q_proj): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (out_proj): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                )
                (layer_norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
                (mlp): Idefics3VisionMLP(
                  (activation_fn): GELUTanh()
                  (fc1): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=3072, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=3072, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (fc2): lora.Linear(
                    (base_layer): Linear(in_features=3072, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=3072, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                )
                (layer_norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
              )
            )
          )
          (post_layernorm): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        )
        (connector): Idefics3Connector(
          (modality_projection): Idefics3SimpleMLP(
            (proj): lora.Linear(
              (base_layer): Linear(in_features=12288, out_features=576, bias=False)
              (lora_dropout): ModuleDict(
                (default): Dropout(p=0.05, inplace=False)
              )
              (lora_A): ModuleDict(
                (default): Linear(in_features=12288, out_features=16, bias=False)
              )
              (lora_B): ModuleDict(
                (default): Linear(in_features=16, out_features=576, bias=False)
              )
              (lora_embedding_A): ParameterDict()
              (lora_embedding_B): ParameterDict()
              (lora_magnitude_vector): ModuleDict()
            )
          )
        )
        (text_model): LlamaModel(
          (embed_tokens): Embedding(49280, 576, padding_idx=2)
          (layers): ModuleList(
            (0-29): 30 x LlamaDecoderLayer(
              (self_attn): LlamaAttention(
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=576, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=576, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (k_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=192, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=192, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=192, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=192, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (o_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=576, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=576, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (mlp): LlamaMLP(
                (gate_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=1536, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1536, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (up_proj): lora.Linear(
                  (base_layer): Linear(in_features=576, out_features=1536, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=576, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1536, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (down_proj): lora.Linear(
                  (base_layer): Linear(in_features=1536, out_features=576, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1536, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=576, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (act_fn): SiLUActivation()
              )
              (input_layernorm): LlamaRMSNorm((576,), eps=1e-05)
              (post_attention_layernorm): LlamaRMSNorm((576,), eps=1e-05)
            )
          )
          (norm): LlamaRMSNorm((576,), eps=1e-05)
          (rotary_emb): LlamaRotaryEmbedding()
        )
      )
      (lm_head): Linear(in_features=576, out_features=49280, bias=False)
    )
  )
)

In [21]:
from PIL import Image
import io

example = train_dataset[0]

img = example["images"][0]

if img["bytes"] is not None:
    image = Image.open(io.BytesIO(img["bytes"])).convert("RGB")
else:
    image = Image.open(img["path"]).convert("RGB")

print(example["messages"][1]["content"][0]["text"])

# PUZZLE MADNESS

Daily Medium Mathdoku Puzzle for Friday 18th June 2021

![img_1](322,382,701,675)

![img_2](322,382,701,675)

In [26]:
from pprint import pprint

sample = train_dataset[0]

pprint(sample)

{'content_list': '[{"type": "text", "text": "PUZZLE MADNESS ", "text_level": '
                 '1, "page_idx": 0}, {"type": "text", "text": "Daily Medium '
                 'Mathdoku Puzzle for Friday 18th June 2021 ", "page_idx": 0}, '
                 '{"type": "image", "img_path": '
                 '"images/11494ec3b1bce232bc8b9e151013523734d29142cd27657caeeb5ce3cfe5128a.jpg", '
                 '"img_caption": [], "img_footnote": [], "page_idx": 0}]',
 'equations': '[]',
 'html': '<div class="pdf-page">\n'
         '<h1>PUZZLE MADNESS</h1>\n'
         '<p>Daily Medium Mathdoku Puzzle for Friday 18th June 2021</p>\n'
         '<figure><img data-bbox="322,382,701,675" />\n'
         '</figure>\n'
         '<figure><img data-bbox="322,382,701,675" />\n'
         '</figure>\n'
         '</div>',
 'html_compact': '<div class="page">\n'
                 '<h1 class="title" bbox="166,215,701,73">PUZZLE MADNESS</h1>\n'
                 '<p class="text" bbox="121,325,779,30">Daily Medium Mathdoku '
                 'Puzzle for Friday 18th June 2021</p>\n'
                 '<figure class="image" bbox="322,382,379,293"></figure>\n'
                 '<figure class="image" bbox="322,382,379,293"></figure>\n'
                 '</div>',
 'html_with_coordinates': '<div class="pdf-page">\n'
                          '<h1 class="pdf-title" data-x="166" data-y="215" '
                          'data-width="701" data-height="73">PUZZLE '
                          'MADNESS</h1>\n'
                          '<p class="pdf-text" data-x="121" data-y="325" '
                          'data-width="779" data-height="30">Daily Medium '
                          'Mathdoku Puzzle for Friday 18th June 2021</p>\n'
                          '<figure class="pdf-image" data-x="322" data-y="382" '
                          'data-width="379" data-height="293"><img '
                          'data-bbox="322,382,701,675" />\n'
                          '</figure>\n'
                          '<figure class="pdf-image" data-x="322" data-y="382" '
                          'data-width="379" data-height="293"><img '
                          'data-bbox="322,382,701,675" />\n'
                          '</figure>\n'
                          '</div>',
 'id': '00006_page_0000',
 'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1993x2579 at 0x23222F57F50>,
 'images': [{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x07\xc9'
                      b'\x00\x00\n\x13\x08\x02\x00\x00\x008J\xf4'
                      b"\xd6\x00\x01\x00\x00IDATx\x9c\xec\xdd\xe9s\\\xe7\x95'h"
                      b'\xe4\xbe"\xb1\x83\x00wR\x14I\x91\xb2$[\x96-\xd9\xaary'
                      b'\xa9ru\xb8\xabbb"\xa6>\xce\x7f7\xd1\x9f\xa6'
                      b'\xa3\xa2g\xbak\xda\xdd\xaerYRY\xd6.\x8a+'
                      b'\xb8\x81\x04\x08\x80\xd8\x91\xfbzs\xc2\xb8v6\x8b\xf2'
                      b'\xc2\x94\x08\x02 \x9e\xe7\x83\x82\xba\x002\xdf|\x91\x00'
                      b'n\xfe\xee\xc9s"\xddnw\x00\x00\x00\x00\x00\x00x'
                      b"b\xd1'\xffT\x00\x00\x00\x00\x00@\xb6\x0e\x00\x00\x00"
                      b'\x00\x00}S\xb7\x0e\x00\x00\x00\x00\x00\xfd'
                      b'\x91\xad\x03\x00\x00\x00\x00@\x7fd\xeb\x00'
                      b'\x00\x00\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00'
                      b'\x00\xf4G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91'
                      b'\xad\x03\x00\x00\x00\x00@\x7fd\xeb\x00\x00'
                      b'\x00\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00'
                      b'\xf4G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad'
                      b'\x03\x00\x00\x00\x00@\x7fd\xeb\x00\x00\x00'
                      b'\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00\xf4'
                      b'G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad\x03'
                      b'\x00\x00\x00\x00@\x7fd\xeb\x00\x00\x00\x00'
                      b'\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00\xf4G'
                      b'\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad\x03\x00'
                      b'\x00\x00\x00@\x7fd\xeb\x00\x00\x00\x00\x00\xd0\x1f\xd9:'
                      b'\x00\x00\x00\x00\x00\xf4G\xb6\x0e\x00\x00\x00'
                      b'\x00\x00\xfd\x91\xad\x03\x00\x00\x00\x00@\x7f'
                      b'd\xeb\x00\x00\x00\x00\x00\xd0\x1f\xd9:\x00'
                      b'\x00\x00\x00\x00\xf4G\xb6\x0e\x00\x00\x00\x00'
                      b'\x00\xfd\x91\xad\x03\x00\x00\x00\x00@\x7fd'
                      b'\xeb\x00\x00\x00\x00\x00\xd0\x1f\xd9:\x00\x00'
                      b'\x00\x00\x00\xf4G\xb6\x0e\x00\x00\x00\x00\x00'
                      b'\xfd\x91\xad\x03\x00\x00\x00\x00@\x7fd\xeb'
                      b'\x00\x00\x00\x00\x00\xd0\x1f\xd9:\x00\x00\x00'
                      b'\x00\x00\xf4G\xb6\x0e\x00\x00\x00\x00\x00\xfd'
                      b'\x91\xad\x03\x00\x00\x00\x00@\x7fd\xeb\x00'
                      b'\x00\x00\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00'
                      b'\x00\xf4G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91'
                      b'\xad\x03\x00\x00\x00\x00@\x7fd\xeb\x00\x00'
                      b'\x00\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00'
                      b'\xf4G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad'
                      b'\x03\x00\x00\x00\x00@\x7fd\xeb\x00\x00\x00'
                      b'\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00\xf4'
                      b'G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad\x03'
                      b'\x00\x00\x00\x00@\x7fd\xeb\x00\x00\x00\x00'
                      b'\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00\xf4G'
                      b'\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad\x03\x00'
                      b'\x00\x00\x00@\x7fd\xeb\x00\x00\x00\x00\x00\xd0\x1f\xd9:'
                      b'\x00\x00\x00\x00\x00\xf4G\xb6\x0e\x00\x00\x00'
                      b'\x00\x00\xfd\x91\xad\x03\x00\x00\x00\x00@\x7f'
                      b'd\xeb\x00\x00\x00\x00\x00\xd0\x1f\xd9:\x00'
                      b'\x00\x00\x00\x00\xf4G\xb6\x0e\x00\x00\x00\x00'
                      b'\x00\xfd\x91\xad\x03\x00\x00\x00\x00@\x7fd'
                      b'\xeb\x00\x00\x00\x00\x00\xd0\x1f\xd9:\x00\x00'
                      b'\x00\x00\x00\xf4G\xb6\x0e\x00\x00\x00\x00\x00'
                      b'\xfd\x91\xad\x03\x00\x00\x00\x00@\x7fd\xeb'
                      b'\x00\x00\x00\x00\x00\xd0\x1f\xd9:\x00\x00\x00'
                      b'\x00\x00\xf4G\xb6\x0e\x00\x00\x00\x00\x00\xfd'
                      b'\x91\xad\x03\x00\x00\x00\x00@\x7fd\xeb\x00'
                      b'\x00\x00\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00'
                      b'\x00\xf4G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91'
                      b'\xad\x03\x00\x00\x00\x00@\x7fd\xeb\x00\x00'
                      b'\x00\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00'
                      b'\xf4G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad'
                      b'\x03\x00\x00\x00\x00@\x7fd\xeb\x00\x00\x00'
                      b'\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00\xf4'
                      b'G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad\x03'
                      b'\x00\x00\x00\x00@\x7fd\xeb\x00\x00\x00\x00'
                      b'\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00\xf4G'
                      b'\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad\x03\x00'
                      b'\x00\x00\x00@\x7fd\xeb\x00\x00\x00\x00\x00\xd0\x1f\xd9:'
                      b'\x00\x00\x00\x00\x00\xf4G\xb6\x0e\x00\x00\x00'
                      b'\x00\x00\xfd\x91\xad\x03\x00\x00\x00\x00@\x7f'
                      b'd\xeb\x00\x00\x00\x00\x00\xd0\x1f\xd9:\x00'
                      b'\x00\x00\x00\x00\xf4G\xb6\x0e\x00\x00\x00\x00'
                      b'\x00\xfd\x91\xad\x03\x00\x00\x00\x00@\x7fd'
                      b'\xeb\x00\x00\x00\x00\x00\xd0\x1f\xd9:\x00\x00'
                      b'\x00\x00\x00\xf4G\xb6\x0e\x00\x00\x00\x00\x00'
                      b'\xfd\x91\xad\x03\x00\x00\x00\x00@\x7fd\xeb'
                      b'\x00\x00\x00\x00\x00\xd0\x1f\xd9:\x00\x00\x00'
                      b'\x00\x00\xf4G\xb6\x0e\x00\x00\x00\x00\x00\xfd'
                      b'\x91\xad\x03\x00\x00\x00\x00@\x7fd\xeb\x00'
                      b'\x00\x00\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00'
                      b'\x00\xf4G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91'
                      b'\xad\x03\x00\x00\x00\x00@\x7fd\xeb\x00\x00'
                      b'\x00\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00'
                      b'\xf4G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad'
                      b'\x03\x00\x00\x00\x00@\x7fd\xeb\x00\x00\x00'
                      b'\x00\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00\xf4'
                      b'G\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad\x03'
                      b'\x00\x00\x00\x00@\x7fd\xeb\x00\x00\x00\x00'
                      b'\x00\xd0\x1f\xd9:\x00\x00\x00\x00\x00\xf4G'
                      b'\xb6\x0e\x00\x00\x00\x00\x00\xfd\x91\xad\x03\x00'
                      b'\x00\x00\x00@\x7fd\xeb\x00\x00\x00\x00\x00\xd0\x1f\xd9:'
                      b'\x00\x00\x00\x00\x00\xf4G\xb6\x0e\x00\x00\x00'
                      b'\x00\x00\xfd\x91\xad\x03\x00\x00\x00\x00@\x7f'
                      b'd\xeb\x00\x00\x00\x00\x00\xd0\x1f\xd9:\x00'
                      b'\x00\x00\x00\x00\xf4G\xb6\x0e\x00\x00\x00\x00'
                      b'\x00\xfd\x91\xad\x03\x00\x00\x00\x00@\x7fd'
                      b'\xeb\x00\x00\x00\x00\x00 [\x07\x00\x00\x00'
                      b'\x00\x80\x9d\xa4n\x1d\x00\x00\x00\x00\x00\xfa#[\x07\x00'
                      b'\x00\x00\x00\x80\xfe\xc8\xd6\x01\x00\x00\x00\x00'
                      b'\xa0?\xb2u\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00\x00'
                      b'\x00\x00\xfa#[\x07\x00\x00\x00\x00\x80\xfe'
                      b'\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2u\x00'
                      b'\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00\x00\x00\x00\xfa#['
                      b'\x07\x00\x00\x00\x00\x80\xfe\xc8\xd6\x01\x00\x00'
                      b'\x00\x00\xa0?\xb2u\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00'
                      b'\x00\x00\x00\x00\xfa#[\x07\x00\x00\x00\x00'
                      b'\x80\xfe\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2'
                      b'u\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00'
                      b'\x00\x00\x00\xfa#[\x07\x00\x00\x00\x00\x80'
                      b'\xfe\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2u'
                      b'\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00\x00'
                      b'\x00\x00\xfa#[\x07\x00\x00\x00\x00\x80\xfe'
                      b'\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2u\x00'
                      b'\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00\x00\x00\x00\xfa#['
                      b'\x07\x00\x00\x00\x00\x80\xfe\xc8\xd6\x01\x00\x00'
                      b'\x00\x00\xa0?\xb2u\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00'
                      b'\x00\x00\x00\x00\xfa#[\x07\x00\x00\x00\x00'
                      b'\x80\xfe\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2'
                      b'u\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00'
                      b'\x00\x00\x00\xfa#[\x07\x00\x00\x00\x00\x80'
                      b'\xfe\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2u'
                      b'\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00\x00'
                      b'\x00\x00\xfa#[\x07\x00\x00\x00\x00\x80\xfe'
                      b'\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2u\x00'
                      b'\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00\x00\x00\x00\xfa#['
                      b'\x07\x00\x00\x00\x00\x80\xfe\xc8\xd6\x01\x00\x00'
                      b'\x00\x00\xa0?\xb2u\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00'
                      b'\x00\x00\x00\x00\xfa#[\x07\x00\x00\x00\x00'
                      b'\x80\xfe\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2'
                      b'u\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00'
                      b'\x00\x00\x00\xfa#[\x07\x00\x00\x00\x00\x80'
                      b'\xfe\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2u'
                      b'\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00\x00'
                      b'\x00\x00\xfa#[\x07\x00\x00\x00\x00\x80\xfe'
                      b'\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2u\x00'
                      b'\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00\x00\x00\x00\xfa#['
                      b'\x07\x00\x00\x00\x00\x80\xfe\xc8\xd6\x01\x00\x00'
                      b'\x00\x00\xa0?\xb2u\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00'
                      b'\x00\x00\x00\x00\xfa#[\x07\x00\x00\x00\x00'
                      b'\x80\xfe\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2'
                      b'u\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00'
                      b'\x00\x00\x00\xfa#[\x07\x00\x00\x00\x00\x80'
                      b'\xfe\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2u'
                      b'\x00\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00\x00'
                      b'\x00\x00\xfa#[\x07\x00\x00\x00\x00\x80\xfe'
                      b'\xc8\xd6\x01\x00\x00\x00\x00\xa0?\xb2u\x00'
                      b'\x00\x00\x00\x00\xe8\x8fl\x1d\x00\x00\x00\x00\x00\xfa#['
                      b'\x07\x00\x00\x00\x00\x80\xfe\xc8\xd6\x01\x00\x00'
                      b'\x00\x00\xa0?\xf1>?\x1f\x00\x00\xd8\xd3\xba\xdd\xee\xc0'
                      b'\xc0@\x10\x04\xddm\xbb\xbd\x9c},\x12\x89\x84\xff\r'
                      b'=z\x10\x00\x00d\xeb\x00\x00\xf0\\\t\x82\xa0\xd9l...n'
                      b'll\x94J\xa5\xdd^\xce\xbe\x94H$\xe2\xf1x"\x91\xc8d2'
                      b'\xb9\\\xaeP(d2\x99D"!X\x07\x00\xa0G\xb6\x0e\x00\x00'
                      b'\xcf\x89\xb0J}kk\xeb\xc1\x83\x07\xbf\xf9\xcdo\xee'
                      b'\xdf\xbf\xbf\xb5\xb5\xb5\xdb\x8b\xda\xc7\xd9z'
                      b'2\x99\x0c\x83\xf5\x91\x91\x91\xe1\xdf\x1b\x1a'
                      b'\x1a\xca\xe7\xf3\xa9T*\x91H(c\x07\x008\xc8d'
                      b'\xeb\x00\x00\xf0\xfc\xe8v\xbb\xf3\xf3\xf3\xff'
                      b'\xfa\xaf\xff\xfa\x9f\xfe\xd3\x7f\xba~\xfdz\xadV\xdb\xed'
                      b'\x15\xedKa\x13\x98X,\x96L&\xb3\xd9l.\x97\x9b\x9e\x9e>'
                      b'y\xf2\xe47\xbe\xf1\x8d\xf3\xe7\xcf\xbf\xf0'
                      b'\xc2\x0b\x13\x13\x13\x85B!\x1a5\xbf\n\x00\xe0\xe0\x92'
                      b'\xad\x03\x00\xc0s"\x08\x82v\xbb}\xff\xfe\xfd\x8f>'
                      b'\xfa\xe8\xc1\x83\x07\xe5r\xb9\xddn\xef\xf6\xa2\xf6w\xbc'
                      b'^\xaf\xd7\xab\xd5\xea\xe6\xe6\xe6\xc6\xc6\xc6'
                      b"\xdc\xdc\xdc\xd5\xabW'&&\x0e\x1d:\xf4\xe2\x8b/"
                      b'\x9e={\xf6\xcc\x993\xd3\xd3\xd3\xc3\xc3\xc3\xd1m\xbb'
                      b'\xbdd\x00\x00\x9e)\xd9:\x00\x00<?:\x9d\xce\xda'
                      b'\xda\xda\xec\xecl\xb1Xl\xb5Z\xbb\xbd\x9c}\xdf`'
                      b'\xa7\xd3\xe9\x84\xdbX*\x95\x1e>|x\xfb\xf6\xedT'
                      b'*\x95\xcb\xe5N\x9f>\xfd\xd2K/\xbd\xf2\xca+/\xbd\xf4RX'
                      b'\xc6\x9e\xcb\xe5\x92\xc9\xa4.1\x00\x00\x07\x87l\x1d\x00'
                      b'\x00\x9e\xc3\xea\xf50\x1a\xe6\xe9\xeav\xbb\x8dF\xa3\xd9'
                      b'l^\xbat\xe9\xd6\xad[\xef\xbc\xf3\xce\xcb/\xbf\xfc'
                      b'\xdd\xef~\xf7\xaf\xfe\xea\xaf\xce\x9c9399i\xc3'
                      b'\x01\x00\x0e\x0e\xd9:\x00\x00<\xe7\xe2\xf1x*\x95\x8a'
                      b'F\xa3\x91Hd\xb7\xd7\xb2?t\x7f/\x08\x82\xce\xb6'
                      b' \x08\xc2\xcb\x15\xe1\xf10a\xafV\xab\xadVku'
                      b'u\xf5\xde\xbd{\xdf\xfe\xf6\xb7\xdfx\xe3\x8d\xe3\xc7\x8f'
                      b'\x0f\r\r\xc5\xe3^g\x01\x00<\xff\x9c\xf3\x01\x00\xc0'
                      b"\xf3,\x12\x89$\x93\xc9\xe1\xe1\xe1x<\xae'\xf8\x13"
                      b'\n\xb6u\xbb\xddN\xa7\xd3n\xb7\x9b\xdb\xc2\x84=\xd4'
                      b'\xaba\x9f\x9f\x9f_ZZ\x9a\x99\x99\xb9\x7f\xff~\xb1'
                      b'X\xfc\xfe\xf7\xbf\xff\xc2\x0b/\x8c\x8d\x8dE"\x11\xbb'
                      b'\r\x00\xf0|\x93\xad\x03\x00\xc0s.\x95J\x8d\x8d\x8d'
                      b'\xa5R)\xf5\xd4O(L\xcf{!{\xbb\xdd\x0e\x87\x9aV\xab\xd5'
                      b'Z\xadV\xaf\xd7{\x9f000\xd0n\xb7\xb7\xb6\xb6'
                      b'>\xfa\xe8\xa3\xc5\xc5\xc5\xb9\xb9\xb9\x1f\xfe'
                      b'\xf0\x87?\xfe\xf1\x8f\xd3\xe9\xb4l\x1d\x00\xe0\xf9&['
                      b'\x07\x00\x80\xe7Y$\x12\x89\xc5b\xc9dR\xb6\xfe\xe4'
                      b'z\xdd\xea{\xcda\xd2\xe9t&\x93\xc9\xe7\xf3\xf5z'
                      b'\xbdV\xabU\xab\xd5\xb0-L\xf8\x99\xedv{cc\xa3V\xab\r'
                      b'\x0c\x0c\xd4\xeb\xf5V\xab\xf5\xdak\xaf\x1d?~<\x99'
                      b'L\xea\xc3\x03\x00\xf0\xbc\x92\xad\x03\x00\x00\xfc;\xbd@'
                      b'\xbc\xf7\x8fx<\x9eN\xa7\xbb\xddn\xbb\xddn4\x1a'
                      b'\x1b\x1b\x1b[[[\xe5r\xb9\xd5j\x855\xecA\x10T\xab\xd5/'
                      b'\xbe\xf8bcccii\xa9\xdb\xed\xe6r\xb9\x89\x89\x89x<.'
                      b'^\x07\x00x.\xc9\xd6\x01\x00\x00\x9eH$\x12\t\xdb'
                      b'\xd6G\xa3\xd1\\.W.\x97\x8b\xc5b\xa9Tj\xb5Z\xbdI\xa7'
                      b'+++\x1f|\xf0A6\x9b-\x97\xcb?\xfb\xd9\xcfFFF\x92'
                      b'\xc9\xa4\xfd\x05\x00x\xfe\xc8\xd6\x01\x00\x00'
                      b'\xfe\xbc\xb0\xfc<\x1cR\x1a\x8dF\xc36;\x89D"'
                      b'\x1e\x8f\x97J\xa5f\xb3\xd9n\xb7\xc3\x9e0\x0f\x1f>'
                      b'\xfc\xe0\x83\x0fb\xb1\xd8\xc4\xc4\xc4+\xaf\xbcr\xf4\xe8'
                      b'\xd1h4\xaaz\x1d\x00\xe09#[\x07\x00\x00\xe8O'
                      b"\x18\xaf'\x12\x89T*\x95\xcb\xe5\x1e>|\xb8\xb5\xb5"
                      b'\x15f\xeba\xf5\xfa\x9d;w:\x9dN*\x95J&\x93\x93\x93\x93'
                      b'\xc9dR\xbc\x0e\x00\xf0\x9c\x91\xad\x03\x00\x00|E\xb1'
                      b'X,\x93\xc9LLL$\x12\x89h4Z\xadV;\x9dN\xf8\xa1'
                      b'\xb5\xb5\xb5\xf7\xde{\xef\xf0\xe1\xc3\xc3\xc3\xc3\x17/^'
                      b"\xccf\xb3J\xd7\x01\x00\x9e'\xb2u\x00\x00\x80\xaf("
                      b'\xac^\x1f\x1c\x1c\x0c\xcb\xd5\xbb\xddn\xadV\x0b\xe3\xf5'
                      b'J\xa5r\xe7\xce\x9d\xdf\xfc\xe67\xe3\xe3\xe3\x13\x13\x13'
                      b'\xd3\xd3\xd3\x99L\xc6F\x03\x00<7d\xeb\x00\x00\x00'
                      b'_K,\x16\xcb\xe7\xf3\x89D"\x08\x82n\xb7[\xa9'
                      b'T\xc2\xa8\xbd\xd5j}\xf6\xd9g\xf1x\xfc\xa5\x97^'
                      b'\xca\xe5r\xb2u\x00\x80\xe7\x89l\x1d\x00\x00\xe0\xab\x0b'
                      b';\xbd\xc4b\xb1T*522\x12\x04A8\xd7\xb4\xdb\xed\x0e\x0c'
                      b'\x0clmm\xdd\xb9s\xe7_\xff\xf5_3\x99\xcc\xe8\xe8h,\x16'
                      b'\x8bF\xa3\xb6\x1b\x00\xe09\xe0\xac\x0e\x00\x00\xe0k\xbf'
                      b'\xb2\x8aF\xe3\xf1\xf8\xe0\xe0\xe0\xd0\xd0PX\xc3\x1e\x1e'
                      b'o6\x9bKKK\xef\xbd\xf7\xde\xd5\xabW\x8b\xc5bo\xde)\x00'
                      b'\x00\xfb\x9dl\x1d\x00\x00\xe0\xe9\x08\xe3\xf5'
                      b'\x89\x89\x89L&\xd3\x9b\\Z\xa9T\xaen\xbb\x7f\xff'
                      b'~\xbd^\xb7\xd7\x00\x00\xcf\x07\xd9:\x00\x00\xc0S\x10'
                      b'\x89D\xc2\xd1\xa6\x85B!\x97\xcb\xa5R\xa9\xf0x\xa7'
                      b'\xd3\xd9\xdc\xdc\xbcy\xf3\xe6\xa7\x9f~\xba'
                      b'\xb5\xb5\x15\x04\x81\xed\x06\x00x\x0e\xc8\xd6'
                      b'\x01\x00\x00\x9e\x9ax<\x9e\xc9d\xf2\xf9|6\x9b\r'
                      b'K\xd7\xc3\xa1\xa6\xb3\xb3\xb3\x1f}\xf4\xd1\xea\xeaj\xab'
                      b'\xd5\xb2\xdd\x00\x00\xcf\x01\xd9:\x00\x00\xc0'
                      b'\xd3\x14\x89D\xf2\xf9|\xa1PH$\x12\xbd\xce0\x0f'
                      b'\x1f>\xfc\xe2\x8b/\xe6\xe7\xe7\x8b\xc5\xa2\xed\x06\x00x'
                      b'\x0e\xc8\xd6\x01\x00\x00\x9e\x9a\xc8\xb6t:\x9d\xcdf\xd3'
                      b'\xe9t,\x16\x0b\x8f\x97\xcb\xe5\xc5\xc5\xc5{\xf7\xee\xad'
                      b'\xad\xad\xd9n\x00\x80\xe7\x80l\x1d\x00\x00\xe0)K$'
                      b'\x12\xe9t:\x93\xc9\xc4\xe3\xf1\xf0H\xb3\xd9,\x16\x8b'
                      b'\xb3\xb3\xb3KKK\xddm6\x1d\x00`_\x93\xad\x03\x00\x00<}'
                      b'\xf1x|pp0\x99L\xf6\x8e\xd4\xeb\xf5\xbbw\xef.,,\xb4'

In [27]:
print(train_dataset.column_names)

['id', 'image', 'pdf_name', 'page_number', 'page_size', 'layout', 'content_list', 'middle', 'model', 'markdown', 'html', 'html_with_coordinates', 'html_compact', 'raw_md', 'lines', 'images', 'equations', 'tables', 'pdf_info', 'vqa', 'messages']

In [29]:
print(len(train_dataset))

100

In [26]:
print(type(train_dataset[0]["images"]))
print(type(train_dataset[0]["images"][0]))

<class 'list'>
<class 'dict'>

In [27]:
print(train_dataset[0]["images"][0].keys())

dict_keys(['path', 'bytes'])

In [39]:
processor.image_processor.size = {
    "height": 384,
    "width": 384
}

In [43]:
processor.image_processor.max_image_size = {
    "longest_edge": 384
}

In [44]:
batch = collate_fn([train_dataset[0]])

for k,v in batch.items():
    print(k, v.shape)

input_ids torch.Size([1, 160])
attention_mask torch.Size([1, 160])
pixel_values torch.Size([1, 1, 3, 384, 384])
pixel_attention_mask torch.Size([1, 1, 384, 384])
labels torch.Size([1, 160])

In [45]:
model.gradient_checkpointing_enable()